#!/bin/sh
# install.sh — register the BMS collector with Venus OS's daemontools supervisor.
#
# Everything lives under /data so it survives firmware updates. The only thing
# outside /data is a symlink into /service, recreated at each boot via
# /data/rc.local.
#
#   sh /data/bms/install.sh                      install, or update in place
#   sh /data/bms/install.sh --bind 127.0.0.1     restrict API to this GX
#   sh /data/bms/install.sh --interval 120       poll less often
#   sh /data/bms/install.sh --tz Europe/Lisbon   if the vessel relocates
#   sh /data/bms/install.sh --show               print current settings, exit
#   sh /data/bms/install.sh --remove             stop and unregister
#
# Re-running preserves whatever settings are already in place; only the values
# passed on the command line change. This avoids an upgrade silently reverting
# the bind address and taking the dashboard offline.

set -e
BMS_DIR=/data/bms
SVC_NAME=bms-collector
SVC_DIR=$BMS_DIR/service
RUN=$SVC_DIR/run
RC=/data/rc.local

# --- defaults for a fresh install --------------------------------------
BIND=0.0.0.0
PORT=8088
INTERVAL=60
SETTLE=12
PRUNE_DAYS=30
TZONE=America/Los_Angeles  # change to your timezone

# --- inherit whatever is already installed -----------------------------
if [ -f "$RUN" ]; then
    v=$(sed -n 's/.*--bind[ ]\{1,\}\([^ \\]*\).*/\1/p' "$RUN" | head -n 1); [ -n "$v" ] && BIND=$v
    v=$(sed -n 's/.*--port[ ]\{1,\}\([^ \\]*\).*/\1/p' "$RUN" | head -n 1); [ -n "$v" ] && PORT=$v
    v=$(sed -n 's/.*--interval[ ]\{1,\}\([^ \\]*\).*/\1/p' "$RUN" | head -n 1); [ -n "$v" ] && INTERVAL=$v
    v=$(sed -n 's/.*--settle[ ]\{1,\}\([^ \\]*\).*/\1/p' "$RUN" | head -n 1); [ -n "$v" ] && SETTLE=$v
    v=$(sed -n 's/.*--prune-days[ ]\{1,\}\([^ \\]*\).*/\1/p' "$RUN" | head -n 1); [ -n "$v" ] && PRUNE_DAYS=$v
    v=$(sed -n 's/^export TZ=\(.*\)$/\1/p' "$RUN" | head -n 1); [ -n "$v" ] && TZONE=$v
fi

# --- command line overrides --------------------------------------------
ACTION=install
while [ $# -gt 0 ]; do
    case "$1" in
        --remove)       ACTION=remove ;;
        --show)         ACTION=show ;;
        --bind)         BIND=$2; shift ;;
        --port)         PORT=$2; shift ;;
        --interval)     INTERVAL=$2; shift ;;
        --settle)       SETTLE=$2; shift ;;
        --prune-days)   PRUNE_DAYS=$2; shift ;;
        --tz)           TZONE=$2; shift ;;
        -h|--help)      sed -n '2,18p' "$0"; exit 0 ;;
        *)              echo "Unknown option: $1" >&2; exit 1 ;;
    esac
    shift
done

show_settings() {
    echo "  bind        $BIND"
    echo "  port        $PORT"
    echo "  interval    ${INTERVAL}s between cycles"
    echo "  settle      ${SETTLE}s between packs"
    echo "  prune       keep ${PRUNE_DAYS} days of raw samples"
    echo "  timezone    $TZONE"
}

if [ "$ACTION" = "show" ]; then
    echo "Current settings:"
    show_settings
    exit 0
fi

if [ "$ACTION" = "remove" ]; then
    echo "Stopping and removing $SVC_NAME..."
    svc -d /service/$SVC_NAME 2>/dev/null || true
    rm -f /service/$SVC_NAME
    sed -i "\|$SVC_DIR|d" $RC 2>/dev/null || true
    echo "Removed. The database and scripts in $BMS_DIR are untouched."
    exit 0
fi

# --- sanity checks -----------------------------------------------------
for f in bms_service.py litime_bluez.py packs.json; do
    if [ ! -f "$BMS_DIR/$f" ]; then
        echo "ERROR: $BMS_DIR/$f is missing" >&2
        exit 1
    fi
done
[ -f "$BMS_DIR/dashboard.html" ] || \
    echo "NOTE: dashboard.html not found; the web page will 404 but the API will work."

echo "Free space:"
df -h /data | tail -n 1
echo
echo "Settings:"
show_settings
echo

# --- daemontools run scripts -------------------------------------------
mkdir -p $SVC_DIR/log
[ -f "$RUN" ] && cp "$RUN" "$RUN.bak"

cat > $RUN <<EOF
#!/bin/sh
exec 2>&1
# Generated by install.sh — re-running the installer preserves these values.
# Venus OS runs on UTC; this sets the boat's timezone for this service only so
# log lines, the dashboard and the AI summary match what VRM displays.
export TZ=$TZONE
# --bind 0.0.0.0 exposes the read-only API and dashboard to the LAN.
#        127.0.0.1 restricts it to Node-RED on this GX device.
# --settle gives BlueZ time to tear a connection down before the next pack.
exec /usr/bin/python3 $BMS_DIR/bms_service.py \\
    --config $BMS_DIR/packs.json \\
    --db $BMS_DIR/bms.db \\
    --port $PORT \\
    --bind $BIND \\
    --interval $INTERVAL \\
    --settle $SETTLE \\
    --prune-days $PRUNE_DAYS
EOF

cat > $SVC_DIR/log/run <<'EOF'
#!/bin/sh
mkdir -p /var/log/bms-collector
# Rotate at 1 MB, keep 5 files: enough for troubleshooting without filling /var
exec multilog t s1000000 n5 /var/log/bms-collector
EOF

chmod 755 $RUN $SVC_DIR/log/run

# --- boot persistence ---------------------------------------------------
touch $RC
chmod 755 $RC
if ! grep -q "$SVC_DIR" $RC 2>/dev/null; then
    # /service is on the root filesystem and is rebuilt on every boot and
    # firmware update, so the symlink has to be recreated each time.
    echo "ln -s $SVC_DIR /service/$SVC_NAME 2>/dev/null" >> $RC
    echo "Added symlink recreation to $RC"
fi

if [ -L /service/$SVC_NAME ]; then
    echo "Restarting service..."
    svc -t /service/$SVC_NAME 2>/dev/null || true
else
    ln -sf $SVC_DIR /service/$SVC_NAME
    echo "Linked $SVC_DIR -> /service/$SVC_NAME"
fi

sleep 8
echo
echo "--- status ---"
svstat /service/$SVC_NAME || true
echo
echo "--- recent log ---"
tail -n 12 /var/log/bms-collector/current 2>/dev/null || echo "(no log yet, give it a minute)"
echo

cat <<EOT

Dashboard:  http://<gx-ip>:$PORT/
API:        http://127.0.0.1:$PORT/bms/summary?hours=24

  svstat  /service/$SVC_NAME
  svc -t  /service/$SVC_NAME               restart
  svc -d  /service/$SVC_NAME               stop
  tail -f /var/log/$SVC_NAME/current
  $BMS_DIR/bmsq --latest
  $BMS_DIR/bmsq --reliability 24

  sh $BMS_DIR/install.sh --show            show current settings
  sh $BMS_DIR/install.sh --interval 120    change one setting, keep the rest
EOT
